const prizes = [
  {
    id: 1,
    img: "/images/matcha-cookie.png",
    isFlipped: false,
    date: new Date(2024, 4, 6),
    message: "Dinner/late-night snack’s on me babe! Pick anything 💁🏻‍♀️",
    includesModal: true,
    modalMessage:
      "Hi Sunshine! 🌞 I know this month's gonna be tough for you, so for the next 19 days, open a box each day and redeem a little surprise from me :) 🎁 I hope it gives you something to look forward to each day, motivates you and makes you smile every morning before you go study. No cheating! Each box unlocks automatically on its set day only ❗ As for today's treat: your sugar mommy is covering dinner. Any takeout, late-night meal you have in mind? Up to you if you wanna come back before or after dinner.  Just let me know! 💸🍜🍟",
    modalImage: "/images/kermit.gif",
    signedOff: true,
    // modalImage: ["/images/me2.jpg", "/images/me1.jpg"],
    // modalImage: "images/me1.jpg",
    // modalVideo: "/images/test2.MP4",
    // modalAudio: "/images/audio3.m4a",
    outcomeImage: "/images/may6.jpg",
  },
  {
    id: 2,
    img: "/images/cookie.png",
    isFlipped: false,
    date: new Date(2024, 4, 7),
    message: "HOME COOKED MEAL! Please welcome Chef Cherry 👩🏻‍🍳",
    includesModal: true,
    modalMessage:
      "Home-cooked meal from me! Hope it tastes okay LOL. Hey, it’s the effort and intention that counts, right? (Plus me panicking and hoping I don’t accidentally food poison you or something 😌) Enjoy!",
    modalImage: "/images/elmo-on-fire.gif",
    signedOff: true,
    outcomeImage: "/images/may7.jpg",
  },
  {
    id: 3,
    img: "/images/dark-chocolate.png",
    isFlipped: false,
    date: new Date(2024, 4, 8),
    message: "Surprise! Breakfast is Here! 🥐",
    includesModal: true,
    modalMessage:
      "Snuck out and picked up some pastries for you from Brick and Butter Bakehouse this morning. Guess which ones I got. ",
    modalImage: "/images/sassycat.jpg",
    signedOff: true,
    outcomeImage: "/images/may8.jpg",
  },
  {
    id: 4,
    img: "/images/matcha-latte.png",
    isFlipped: false,
    date: new Date(2024, 4, 9),
    message: "You get a custom playlist for studying! 📚",
    modalMessage:
      "Made you a playlist with chill study music, hope it helps you focus! I also threw in some Canto, Taiwanese and Japanese tracks as well. Good luck today!",
    includesModal: true,
    modalIframe: `<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0Jj1w1DL15clDpmDZskfcX?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>`,
    signedOff: false,
  },
  {
    id: 5,
    img: "/images/latte.png",
    isFlipped: false,
    date: new Date(2024, 4, 10),
    message: "The rizz you didn't ask for - Play the audio 🔊",
    includesModal: true,
    modalMessage: "Aura +1000000. 🔥 Just hit play",
    modalImage: "/images/cat-smirk.gif",
    signedOff: false,
    modalAudio: "/images/may10audio.m4a",
  },
  {
    id: 6,
    img: "/images/french-vanilla.png",
    isFlipped: false,
    date: new Date(2024, 4, 11),
    message: "Selfie Drop 📸 You got a mission! ",
    includesModal: true,
    modalMessage:
      "Here’s a selfie of me with half a heart 💕 Mission: Complete the other half and send back a selfie! (Choose whichever pic you want)",
    modalImage: [
      "/images/halfheart3.jpg",
      "/images/halfheart1.jpg",
      "/images/halfheart4.jpg",
    ],
    signedOff: true,
    outcomeImage: "/images/completed-heart.jpg",
  },
  {
    id: 7,
    img: "/images/espresso.png",
    isFlipped: false,
    date: new Date(2024, 4, 12),
    message: "Go treat yourself today! ☕️🍪",
    signedOff: true,
    includesModal: true,
    modalMessage:
      "Just sent you $25! I know you'll be studying all day with your friends, and even though I can't be there to support you in person, make sure to treat yourself to some snacks and drinks at the café. Enjoy it on my behalf. You got this! 💪🏻",
    modalImage: "/images/shove-money.gif",
  },
  // {
  //   id: 6,
  //   img: "/images/hot-tea.png",
  //   isFlipped: false,
  //   date: new Date(2024, 4, 11),
  //   message: "hello world",
  // },
  {
    id: 8,
    img: "/images/black-coffee.png",
    isFlipped: false,
    date: new Date(2024, 4, 13),
    includesModal: true,
    message: "We Too Broke to UberEats 💀",
    modalMessage:
      "I hate cooking so much, BUT we both know we’re broke AF and can’t keep living off 44 nuggets every time. So I’m making us lunch today before our 5-hour ride to Ottawa. Just focus on studying in my room!",
    signedOff: false,
    modalImage: "/images/kermit-freakout-closeup.gif",
  },

  {
    id: 9,
    img: "/images/ice-matcha.png",
    isFlipped: false,
    date: new Date(2024, 4, 14),
    message: "Time for Snack Refill!!! 🍫",
    signedOff: false,
    includesModal: true,
    modalMessage:
      "I think we are low on snacks at home, and you'll need something to snack on while studying over the next few. Snacks are on me today!",
    modalImage: "/images/cat-eating-chips.gif",
  },

  {
    id: 10,
    img: "/images/ice-tea.png",
    isFlipped: false,
    date: new Date(2024, 4, 15),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 11,
    img: "/images/ice-coffee.png",
    isFlipped: false,
    date: new Date(2024, 4, 16),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 12,
    img: "/images/muffin.png",
    isFlipped: false,
    date: new Date(2024, 4, 17),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 13,
    img: "/images/bagel.png",
    isFlipped: false,
    date: new Date(2024, 4, 18),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 14,
    img: "/images/strawberry-shortcake.png",
    isFlipped: false,
    date: new Date(2024, 4, 19),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 15,
    img: "/images/matcha-croissant.png",
    isFlipped: false,
    date: new Date(2024, 4, 20),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 16,
    img: "/images/puff.png",
    isFlipped: false,
    date: new Date(2024, 4, 21),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 17,
    img: "/images/danish.png",
    isFlipped: false,
    date: new Date(2024, 4, 22),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 18,
    img: "/images/brownie.png",
    isFlipped: false,
    date: new Date(2024, 4, 23),
    message: "hello world",
    signedOff: false,
  },
  // {
  //   id: 17,
  //   img: "/images/red-velvet.png",
  //   isFlipped: false,
  //   date: new Date(2024, 4, 23),
  //   message: "hello world",
  // },
  {
    id: 19,
    img: "/images/nic-exam1.png",
    isFlipped: false,
    date: new Date(2024, 4, 23),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 20,
    img: "/images/butterfly.png",
    isFlipped: false,
    date: new Date(2024, 4, 24),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 21,
    img: "/images/onigiri.png",
    isFlipped: false,
    date: new Date(2024, 4, 25),
    message: "hello world",
    signedOff: false,
  },
  {
    id: 22,
    img: "/images/nic-exam2.png",
    isFlipped: false,
    date: new Date(2024, 4, 25),
    message: "hello world",
    signedOff: false,
  },
];

export default prizes;
