const prizes = [
  {
    id: 1,
    img: "/images/matcha-cookie.png",
    isFlipped: false,
    date: new Date(2024, 4, 6),
    message: "hello world",
    includesModal: true,
    modalMessage: "Hihihihihi",
    modalImage: "/images/me2.jpg",
  },
  {
    id: 2,
    img: "/images/cookie.png",
    isFlipped: false,
    date: new Date(2024, 4, 7),
    message: "hello world",
  },
  {
    id: 3,
    img: "/images/dark-chocolate.png",
    isFlipped: false,
    date: new Date(2024, 4, 8),
    message: "hello world",
  },
  {
    id: 4,
    img: "/images/matcha-latte.png",
    isFlipped: false,
    date: new Date(2024, 4, 9),
    message: "hello world",
  },
  {
    id: 5,
    img: "/images/latte.png",
    isFlipped: false,
    date: new Date(2024, 4, 10),
    message: "hello world",
  },
  {
    id: 10,
    img: "/images/french-vanilla.png",
    isFlipped: false,
    date: new Date(2024, 4, 11),
    message: "hello world",
  },
  {
    id: 10,
    img: "/images/espresso.png",
    isFlipped: false,
    date: new Date(2024, 4, 12),
    message: "hello world",
  },
  // {
  //   id: 6,
  //   img: "/images/hot-tea.png",
  //   isFlipped: false,
  //   date: new Date(2024, 4, 11),
  //   message: "hello world",
  // },
  {
    id: 10,
    img: "/images/black-coffee.png",
    isFlipped: false,
    date: new Date(2024, 4, 13),
    message: "hello world",
  },

  {
    id: 7,
    img: "/images/ice-matcha.png",
    isFlipped: false,
    date: new Date(2024, 4, 14),
    message: "hello world",
  },
  {
    id: 8,
    img: "/images/ice-tea.png",
    isFlipped: false,
    date: new Date(2024, 4, 15),
    message: "hello world",
  },
  {
    id: 9,
    img: "/images/ice-coffee.png",
    isFlipped: false,
    date: new Date(2024, 4, 16),
    message: "hello world",
  },
  {
    id: 11,
    img: "/images/muffin.png",
    isFlipped: false,
    date: new Date(2024, 4, 17),
    message: "hello world",
  },
  {
    id: 12,
    img: "/images/bagel.png",
    isFlipped: false,
    date: new Date(2024, 4, 18),
    message: "hello world",
  },
  {
    id: 13,
    img: "/images/strawberry-shortcake.png",
    isFlipped: false,
    date: new Date(2024, 4, 19),
    message: "hello world",
  },
  {
    id: 14,
    img: "/images/matcha-croissant.png",
    isFlipped: false,
    date: new Date(2024, 4, 20),
    message: "hello world",
  },
  {
    id: 15,
    img: "/images/puff.png",
    isFlipped: false,
    date: new Date(2024, 4, 21),
    message: "hello world",
  },
  {
    id: 16,
    img: "/images/danish.png",
    isFlipped: false,
    date: new Date(2024, 4, 22),
    message: "hello world",
  },
  {
    id: 17,
    img: "/images/brownie.png",
    isFlipped: false,
    date: new Date(2024, 4, 23),
    message: "hello world",
  },
  // {
  //   id: 17,
  //   img: "/images/red-velvet.png",
  //   isFlipped: false,
  //   date: new Date(2024, 4, 23),
  //   message: "hello world",
  // },
  {
    id: 18,
    img: "/images/butterfly.png",
    isFlipped: false,
    date: new Date(2024, 4, 23),
    message: "hello world",
  },
  {
    id: 16,
    img: "",
    isFlipped: false,
    date: new Date(2024, 4, 24),
    message: "hello world",
  },
  {
    id: 18,
    img: "/images/onigiri.png",
    isFlipped: false,
    date: new Date(2024, 4, 25),
    message: "hello world",
  },
  {
    id: 18,
    img: "",
    isFlipped: false,
    date: new Date(2024, 4, 25),
    message: "hello world",
  },
];

export default prizes;
